services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthcheckPath: /tasks
    envVars:
      - key: DB_HOST
        value: ${{mysql.MYSQLHOST}}
      - key: DB_USER  
        value: root
      - key: DB_PASSWORD
        value: ${{mysql.MYSQLPASSWORD}}
      - key: DB_NAME
        value: todo_db
      - key: DB_PORT
        value: ${{mysql.MYSQLPORT}}
        
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_URL
        value: ${{backend.url}}
        
  - type: mysql
    name: mysql
    plan: starter
